### ISSUE TITLE
Let's split into two stages

### ISSUE THREAD

**Issue by stikonas** [schierlm/gnu-autogen-bootstrapping#4]
I suggest that we have an option to exit bootstrapping script once `columns`, `getdefs`, `autogen` and `config-tpl.tlib` are built.

So then stage1 would be bootstrapping and stage2 is just a normal build.

**Comment by schierlm** [comment]
Good idea. Not sure whether you want to split after having built the first version of config-tpl.tlib in https://github.com/schierlm/gnu-autogen-bootstrapping/blob/main/bootstrap.sh#L86 (i.e. before running configure et al), or after the real one has been built. In any case, feel free to send a PR.

**Comment by stikonas** [comment]
Hmm, good question. So if I understand correctly, once somebody have fully bootstrapped autogen (i.e. let's say we do upgrade to a new version)then we wouldn't have to build `config-tpl.tlib`. That is why I was thinking we could stop after it.
Though maybe we could split into smaller even steps (prepare source, bootstrap columns, bootstrap getdefs, bootstrap autogen, bootstrap config-tpl.tblib, rebuild) and `bootstrap.sh` would just call them

**Comment by schierlm** [comment]
Ah okay, When from the point "what is special for bootstrapping?"; stopping after the second config-tpl.tlib is correct (as, when bootstrapping from an old version, it will already be there). I was more thinking about making it easy to patch around "tricky" parts of the bootstrap, and from that point of view, getting the configure and bootstrap script working is the harder part - once you got that working, the actual make part is just taking some more computation time and less likely to fail (YMMV).

**Comment by stikonas** [comment]
I see. There is also some point in stopping after `autogen` is bootstrapped. I'm not yet sure what we want to do in live-bootsrap, I can ask @fosslinux what he prefers.
